kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
        - name: {{ .Values.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.name }}
      containers:
        - name: atlantis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ATLANTIS_DATA_DIR
              value: {{ .Values.env.ATLANTIS_DATA_DIR | quote }}
            - name: ATLANTIS_PORT
              value: {{ .Values.env.ATLANTIS_PORT | quote }}
            - name: ATLANTIS_URL
              value: {{ .Values.env.ATLANTIS_URL | quote }}
            - name: ATLANTIS_REPO_ALLOWLIST
              value: {{ .Values.env.ATLANTIS_REPO_ALLOWLIST | quote }}
          envFrom:
            {{- range $val := .Values.vault.secrets }}
            {{- if $val.name }}
            - secretRef:
                name: {{ $val.name }}-secret
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.name }}
              mountPath: /atlantis-data
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: "/"
              port: 4141
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/"
              port: 4141
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 2
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: {{ .Values.name }}
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
