apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.ingress.name }}
  namespace: app
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.name | quote }}
    spec.ingressClassName: "gce"
spec:
  {{- with .Values.ingress.rules }}
  rules:
  {{- toYaml . | nindent 4 }}
  {{- end }}