kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4141
  selector:
    app: {{ .Values.name }}
  type: NodePort
