apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name }}
  annotations:
    ku: ku
    be: be
    daangn: daangna
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.name }}
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo KuBeDaangn
          restartPolicy: OnFailure
