apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wordpress-ethan
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: "standard"
  resources:
    requests:
      storage: 1Gi