apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: crt-d-devops-bastion
spec:
  domains:
    - vault.devops.henesis.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-d-devops-bastion
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ing-d-devops-bastion"
    networking.gke.io/managed-certificates: crt-d-devops-bastion
    networking.gke.io/v1beta1.FrontendConfig: fcf-d-devops-bastion
    spec.ingressClassName: "gce"
spec:
  defaultBackend:
    service:
      name: bastion
      port:
        number: 80
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: fcf-d-devops-bastion
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT