apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, role:operator, role:readonly
    p, role:operator, applications, *, */*, allow

    g, role:devops, role:readonly
    p, role:devops, *, *, */*, allow

    g, role:engineer, role:readonly
    p, role:engineer, applications, *, */*, allow

    g, jmeef0802@gmail.com, role:admin

  scopes: "[email, group]"
