apiVersion: v1
data:
  dex.google.clientId: "NDcwNjY4NzAxNTk2LW03YnJraGMzczVldTR0b3NzdTYwY2NtcDdkdWNiazMyLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t"
  dex.google.clientSecret: "R09DU1BYLTdac1hPeWFGWXhYNVNPQWhicjNxMG8zcTd5SFc="
stringData:
  webhook.github.secret: "aGVuZXNpcy1hcmdvY2Q=" # henesis-argocd
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
---
apiVersion: v1
data:
  AVP_AUTH_TYPE: YXBwcm9sZQ== # approle
  AVP_ROLE_ID: ""
  AVP_SECRET_ID: ""
  AVP_TYPE: dmF1bHQ= # vault
  VAULT_ADDR: aHR0cHM6Ly92YXVsdC5oYWVjaGkuaW86ODIwMC8=
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
