apiVersion: v1
data:
  dex.google.clientId: ""
  dex.google.clientSecret: ""
stringData:
  webhook.github.secret: "" # devops
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
---
apiVersion: v1
data:
  AVP_AUTH_TYPE: YXBwcm9sZQ== # approle
  AVP_ROLE_ID: ""
  AVP_SECRET_ID: ""
  AVP_TYPE: dmF1bHQ= # vault
  VAULT_ADDR: aHR0cHM6Ly92YXVsdC5oYWVjaGkuaW8v
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
