apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-starter
  namespace: {{ template "namespace" . }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
data:
  runner-starter.sh: |
  {{- .Files.Get (printf "runner-starter.sh") | nindent 4 }}