name: commit
inputs:
  service-name:
    required: true
  version:
    required: true
  github-pat:
    required: true

  gcp-project-id:
    required: true
  gcp-service-account:
    required: true
  gcp-workload-identity-provider:
    required: true
  gcp-gar-address:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout zero-trusted-pipeline
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-pat }}

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.gcp-workload-identity-provider }}
        service_account: ${{ inputs.gcp-service-account }}
        access_token_lifetime: 300s

    - name: Login to Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.gcp-gar-address }}
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - id: docker-push-tagged
      name: Tag Docker image and push to Google Artifact Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ inputs.gcp-gar-address }}/${{ inputs.gcp-project-id }}/zero-trusted-pipeline/${{ inputs.service-name }}:${{ inputs.version }}
          ${{ inputs.gcp-gar-address }}/${{ inputs.gcp-project-id }}/zero-trusted-pipeline/${{ inputs.service-name }}:latest