apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: crt-d-devops-iise
  namespace: app
spec:
  domains:
    - api.haechi.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-d-devops-iise
  namespace: app
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ing-d-devops-iise"
    networking.gke.io/managed-certificates: crt-d-devops-iise
    networking.gke.io/v1beta1.FrontendConfig: fcf-d-devops-iise
    spec.ingressClassName: "gce"
spec:
  defaultBackend:
    service:
      name: iise-nginx
      port:
        number: 80
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: fcf-d-devops-iise
  namespace: ops
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT