apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
  {{- include "common.labels" . | indent 4 }}
  namespace: {{ template "namespace" . }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
  {{- include "common.labels" . | indent 4 }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: tcp