apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
  {{- include "common.labels" . | indent 4 }}
  namespace: {{ template "namespace" . }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: {{ .Values.replicas | default 1 }}
  revisionHistoryLimit: 3
  minReadySeconds: {{ .Values.minReadySeconds | default 10 }}
  selector:
    matchLabels:
  {{- include "common.labels" . | indent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
      {{- include "common.labels" . | indent 8}}
    spec:
      volumes:
      {{- if .Values.configmap.enabled | default false }}
        - name: config
          configMap:
            name: {{ template "configmap.name" . }}
            items:
              - key: {{ .Values.configmap.file }}
                path: {{ .Values.configmap.file }}
      {{- end }}
      containers:
        - name: {{ template "name" . }}
          image: "fabiocicerchia/nginx-lua:1.23.3-alpine3.17.2-compat"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done" ]
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            {{- range $val := .Values.vault.secrets }}
            {{- if $val.name }}
            - secretRef:
                name: {{ $val.name }}-secret
            {{- end }}
            {{- end }}
          volumeMounts:
          {{- if .Values.configmap.enabled | default false }}
          - name: config
            mountPath: {{ .Values.configmap.mountPath }}
            readOnly: {{ .Values.configmap.readOnly }}
            subPath: {{ .Values.configmap.file }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 60 }}
      imagePullSecrets:
        - name: dockerconfig-regcred