{{- range $val := .Values.vault.secrets }}
{{- if $val.name }}
apiVersion: v1
data:
  {{- range $k, $v := $val.kv }}
    {{ $k }}: <{{ $v }} | base64encode>
  {{- end }}
kind: Secret
metadata:
  name: {{ $val.name }}-secret
  namespace: app
  annotations:
    avp.kubernetes.io/path: "kubernetes/data/{{ $val.name }}/{{ $.Values.vault.env }}"
type: Opaque
---
{{- end }}
{{- end }}