apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: argocd-server-config
  namespace: argocd
spec:
  iap:
    enabled: false
    oauthclientCredentials:
      secretName: oauth-client-credentials