project: dev

vault:
  enable: true

source:
  cluster: kc-d-devops-main
  branch: main
  namespace: app
  repoURL: https://github.com/PrrrStar/zero-trusted-pipeline
  helm:
    valueFiles:
      - values.dev.yaml

applications:
  iise-nginx:
    enabled: true
    chartPath: charts
    enableAutoSync: true
    valueFilePath: values/iise/values.dev.yaml
