name: deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  deploy-image:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: "iise"
    outputs:
      deploy-env: ${{ steps.version.outputs.deploy-env }}
      version: ${{ github.ref_name }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.7.3
        with:
          method: approle
          url: ${{ secrets.VAULT_ADDR }}
          namespace: ${{ secrets.VAULT_NAMESPACE }}
          #caCertificate: ${{ secrets.VAULT_CA_CERT }}
          jwtTtl: 300
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            github/data/zero-trusted-pipeline GITHUB_USERNAME | GITHUB_USERNAME ;
            github/data/zero-trusted-pipeline GITHUB_PAT | GITHUB_PAT ;
            github/data/zero-trusted-pipeline GCP_PROJECT_ID | GCP_PROJECT_ID ;
            github/data/zero-trusted-pipeline GCP_SA_D_DEVOPS_DEPLOY | GCP_SA_D_DEVOPS_DEPLOY ;
            github/data/zero-trusted-pipeline GCP_WIP_ID | GCP_WIP_ID ;
            github/data/zero-trusted-pipeline GCP_WIP_PROVIDER_ID | GCP_WIP_PROVIDER_ID ;
            github/data/zero-trusted-pipeline GCP_GAR_ADDRESS | GCP_GAR_ADDRESS ;

      - name: Checkout zero-trusted-pipeline
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_PAT }}

      - name: Validate version format
        id: check_version
        uses: ./.github/workflows/actions/validator
        with:
          version: ${{ github.ref_name }}

      - name: Build and push docker image
        id: docker
        uses: ./.github/workflows/actions/gar
        with:
          service-name: ${{ env.SERVICE_NAME }}
          version: ${{ github.ref_name }}
          github-pat: ${{ env.GITHUB_PAT }}

          gcp-project-id: ${{ env.GCP_PROJECT_ID }}
          gcp-service-account: ${{ env.GCP_SA_D_DEVOPS_DEPLOY }}
          gcp-wip-id: ${{ env.GCP_WIP_ID }}
          gcp-wip-provider-id: ${{ env.GCP_WIP_PROVIDER_ID }}
          gcp-gar-address: ${{ env.GCP_GAR_ADDRESS }}

      - name: Update the service version in charts
        uses: ./.github/workflows/actions/github
        with:
          deploy-env: ${{ steps.version.outputs.deploy-env }}
          version: ${{ github.ref_name }}
          github-username: ${{ env.GITHUB_USERNAME }}
          github-pat: ${{ env.GITHUB_PAT }}
          service-name: ${{ env.SERVICE_NAME }}
