name: deploy-test
on:
  workflow_dispatch:
jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        id: test1
        run: |
          echo "Secrets: foo ${{ secrets.foo }}"
          echo "Secrets: foo ${{ secrets.foo }}"
          echo "Secrets: foo ${{ secrets.foo }}"
      - name: Test2
        id: test2
        run: |
          echo "Secrets: foo ${{ secrets.foo }}"
          echo "Secrets: foo ${{ secrets.foo }}"
          echo "Secrets: foo ${{ secrets.foo }}"
